_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES : 10
  PIXEL_MEAN : [103.530, 116.280, 123.675]
  PIXEL_STD : [1.0, 1.0, 1.0]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000

DATASETS:
  TRAIN: ("test_2017_train",)
  TEST: ("test_occlude_2017_val",)

OUTPUT_DIR : "./output_fpn_input_gradcam"